//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptumBots
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appoinment
    {
        public int Id { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> PhysicianID { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Physician Physician { get; set; }
    }
}
