//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptumBots
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physician
    {
        public Physician()
        {
            this.Appoinments = new HashSet<Appoinment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SpecialityID { get; set; }
    
        public virtual ICollection<Appoinment> Appoinments { get; set; }
        public virtual Speciality Speciality { get; set; }
    }
}
